export * from "./header";
export * from "./hero";
export * from "./about";
export * from "./process";
export * from "./portfolio";
export * from "./cta-section";
export * from './whatido';
export * from './contact';
export * from './footer';